### ISSUE TITLE
您好，我使用你这个例子，发现执行generate_train.m和generate_test.m的时候报如下错误，请问应该怎么处理？

### ISSUE THREAD

**Issue by TonyDandelion** [mindcont/SR-Caffe#1]
您好，我使用你这个例子，发现执行generate_train.m和generate_test.m的时候报如下错误，请问应该怎么处理？
错误使用 h5infoc
无法打开文件。文件名可能损坏或包含不受支持的字符。

出错 h5info (line 74)
hinfo = h5infoc(filename,location);

出错 h5disp>display_hdf5 (line 68)
hinfo = h5info(options.Filename,options.Location);

出错 h5disp (line 48)
display_hdf5(options);

出错 generate_train (line 95)
h5disp(savepath);

出错 run (line 96)
evalin('caller', [script ';']);

请问，这种情况该如何解决？

**Comment by mindcont** [comment]
@TonyDandelion 
`h5infoc`报错，貌似是matlab 读取和生成 hdf5文件时出错
请依次检查 对应系统下文件路径的书写，路径中有无中文字符，文件读取位置是否存在

其中matlab路径书写方式
* 在Windows 下
`file = 'H:\user4\matlab\myfile.txt';`
* 在Linux下
`file = fullfile('H:/user4/matlab/myfile.txt')`

> 错误使用 h5infoc
无法打开文件。文件名可能损坏或包含不受支持的字符。

**Comment by TonyDandelion** [comment]
好的，这个问题已解决，谢谢您的解答，还有一个问题想请教您，您项目中利用3x.mat文件重构CNN的demo_SR.m是依据根据训练网络的结构层次来写的吗？我跑了其他的一些SRCNN网络，产生了不同的3x.mat文件，请问怎样才能针对不同项目生产的3x,mat文件写demo_SR.m呢？caffe新手，不懂如何入手，谢谢赐教。

**Comment by mindcont** [comment]
> 您项目中利用3x.mat文件重构CNN的demo_SR.m是依据根据训练网络的结构层次来写的吗？

`3x.mat`  由对应文件夹[saveFilters.m](https://github.com/mindcont/SR-Caffe/blob/master/train/SRCNN-5/saveFilters.m#L51-L57) 生成，它包含已训练网络中的权值(weights) 和 偏置(bias)。

`demo_SR.m` 将视不同的上采样比例，采用不同的`*x.mat`， 例如[Line23-35](https://github.com/mindcont/SR-Caffe/blob/master/train/SRCNN-5/demo/demo_SR.m#L23-L35)

```json
% up_scale = 3;
% model = 'model\9-3-5(ImageNet)\x3.mat';
% up_scale = 3;
% model = 'model\9-1-5(91 images)\x3.mat';
% up_scale = 2;
% model = 'model\9-5-5(ImageNet)\x2.mat'; 
% up_scale = 4;
% model = 'model\9-5-5(ImageNet)\x4.mat';

```
追踪上采样比例因子` up_scale = 3;` 在文件中的出现位置，即可明白如何使用不同的`3x.mat`

BTW, feel free to re-open a closed issue if needed

**Comment by TonyDandelion** [comment]
谢谢您的耐心解答。

**Comment by qihuazhuozhuo** [comment]
> 好的，这个问题已解决，谢谢您的解答，还有一个问题想请教您，您项目中利用3x.mat文件重构CNN的demo_SR.m是依据根据训练网络的结构层次来写的吗？我跑了其他的一些SRCNN网络，产生了不同的3x.mat文件，请问怎样才能针对不同项目生产的3x,mat文件写demo_SR.m呢？caffe新手，不懂如何入手，谢谢赐教。

请问你这个问题是如何解决的呀
