### ISSUE TITLE
test image performance of SR-Caffe in caffe

### ISSUE THREAD

**Issue by robosina** [mindcont/SR-Caffe#2]
Hi,
I want to know is there any way to use extracted weights in caffe and give it an image and run model.forward() and caffe give the de-noised result? I haven't Matlab

**Comment by mindcont** [comment]
Hi,  @robosina 

I suppose you want the "end to end" way, yes, there is a way,but in this repo we don't support.  We just use caffe as training features tools and than use matlab combine features to obtain super-resolution images.

Maybe you can fellow the latest end-to-end approach on ICCV, CVPR and ECCV in the field of super-resolution. 

Cheers up up 🍻💪
